Android/android_advanced.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/project1.md, Android/project1_en.md, Android/project2.md, Android/project2_en.md, Android/setup_ci.md, Android/unit_test.md, Android/unit_test_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md, README.md
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/???)
- init Android Guideline and Define Kotlin Guideline
=> kotlin guide

Laravel/laravel.en.md, Laravel/project1.en.md, Laravel/project2.en.md, Laravel/setup_ci.en.md, Laravel/unitest.en.md, PHP/php.en.md, README.md
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/???)
- Change number items `completed/total` in admin page.
- I edit js file, inject not_vary_normal items in calculate function.
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.
=> Add English language Guide for PHP module

IOS/ios_tutorial.md, IOS/ios_tutorial_en.md
=> Init guide line ios tutorial

IOS/project1.md, IOS/project1_en.md, IOS/project2.md, IOS/project2_en.md, IOS/setup-project/.gitignore, IOS/setup-project/.swiftlint.yml, IOS/setup-project/README.md, IOS/setup-project/pull_request_template.md
=> Init guide line ios project 1 & 2

IOS/ios_advanced _en.md, IOS/ios_advanced.md, IOS/ios_tutorial.md, IOS/ios_tutorial_en.md, Swift/swift.en.md, Swift/swift.md
+ Guide line ios advance
+ Update link documents swift and ios tutorial to training framework 2.0.0
=> Guide line ios advance

README.md
=> Update Readme Root

README.md
=> Update link ios

IOS/setup-project/README.md, IOS/setup-project/install_swiftlint.md, IOS/setup-project/pull_request_template.md
=> Add guideline swiftlint

Git/git_tutorial.md, Git/git_tutorial_en.md, Rails/project1.md, Rails/rails_tutorial.md, Rails/rails_tutorial_en.md, Rails/rspec.md, Rails/rspec_en.md, Ruby/ruby.en.md, Ruby/ruby.md
- Update link document theo version release 2.1
=> update link document for ruby version 2.1

Android/android_advanced.md, Android/android_advanced_en.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/project1.md, Android/project1_en.md, Android/unit-test/unit_test.md, Android/unit-test/unit_test_en.md, IOS/ios_advanced.md, IOS/ios_advanced_en.md, IOS/ios_tutorial.md, IOS/ios_tutorial_en.md, IOS/unit-test/unit_test.md, IOS/unit-test/unit_test_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md, Swift/swift.en.md, Swift/swift.md
Update document for mobile to 2.1
=> Update document for mobile to 2.1

Android/README.md, Android/android_advanced.md, Android/android_advanced_en.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/project1.md, Android/project1_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md
- [Android] Update Master schedule match with TF 1.7
=> [Android] Update For TF ver 1.7

IOS/README.md, IOS/ios_advanced.md, IOS/project2_en.md, Swift/swift.en.md, Swift/swift.md
[iOS] Update Master schedule match with TF 1.7
=> [iOS] Update For TF ver 1.7

Android/android_advanced.md, Android/android_advanced_en.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/project1.md, Android/project1_en.md, Android/project2.md, Android/project2_en.md, Android/setup-project/.sun-ci.yml, Android/setup-project/README.md, IOS/ios_advanced.md, IOS/ios_advanced_en.md, IOS/ios_tutorial.md, IOS/ios_tutorial_en.md, IOS/project1.md, IOS/project1_en.md, IOS/project2.md, IOS/project2_en.md, IOS/setup-project/install_swiftlint.md, IOS/unit-test/unit_test.md, IOS/unit-test/unit_test_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md, Swift/swift.en.md, Swift/swift.md
- Add config Sun*CI for Android Project
- Update link document for Android & iOS TF 2.3
=> [Update] Guideline document Android/iOS with TF 2.3

IOS/ios_advanced.md, IOS/ios_advanced_en.md, IOS/ios_tutorial.md, IOS/ios_tutorial_en.md, IOS/project1.md, IOS/project1_en.md, IOS/project2.md, IOS/project2_en.md, IOS/unit-test/unit_test.md, IOS/unit-test/unit_test_en.md, Swift/swift.en.md, Swift/swift.md
- Update link document match with TF 2.4
- Update guidelines for iOS Tutorial
- Remove referral project in Project 1&2
=> [iOS] Update TF 2.4

Android/android_advanced.md, Android/android_advanced_en.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/unit-test/unit_test.md, Android/unit-test/unit_test_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md
- Update training framework 2.4
- I edit js file, inject not_vary_normal items in calculate function.
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.
=> [android] Update training framework 2.4

Django/api.md, Django/api_en.md, Django/django.md, Django/django_en.md, Django/project2.md, Django/project2_en.md, Python/python.md, Python/python_en.md
- Cập nhật các link tài liệu lấy theo version 2.5 để publish
- Link hiện tại đã out of date
=> Upgrade version 2.5 for link of python module

Android/android_advanced.md, Android/android_advanced_en.md, Android/android_tutorial.md, Android/android_tutorial_en.md, Android/unit-test/unit_test.md, Android/unit-test/unit_test_en.md, Kotlin/kotlin.en.md, Kotlin/kotlin.md
- Cập nhật link tài liệu ver 2.6
=> update URL TF v2.6

Django/api.md, Django/api_en.md, Django/django.md, Django/django_en.md, Django/project2.md, Django/project2_en.md, Git/git_tutorial.md, Git/git_tutorial_en.md, Java/SpringCore_tutorial.md, Java/SpringCore_tutorial_en.md, Java/SpringMVC_tutorial.md, Java/SpringMVC_tutorial_en.md, Java/hibernate_tutorial.md, Java/hibernate_tutorial_en.md, Java/javacore_tutorial.md, Java/javacore_tutorial_en.md, Malaysia_Training/git.md, Malaysia_Training/ruby.md, PHP/php.en.md, Python/python.md, Python/python_en.md, Rails/rails_tutorial.md, Rails/rails_tutorial_en.md, Rails/rspec.md, Rails/rspec_en.md, Ruby/ruby.en.md, Ruby/ruby.md, mysql/mysql.en.md, mysql/mysql.md
update link public traning framework ver[ 2.6 For Trainee](https://drive.google.com/drive/folders/1RMLTxcoBWJh5Xrt1cT_4aGQeVYniQiPP)
=> update link driver ver 2.6

Dart/dart.en.md, Dart/dart.md, Flutter/flutter_adanced.md, Flutter/flutter_adanced_en.md, Flutter/flutter_tutorial.md, Flutter/flutter_tutorial_en.md, Flutter/project1.md, Flutter/project1_en.md
- [Task] Update Flutter Course S*Lean link slide and video
- Change number items `completed/total` in admin page.
- I edit js file, inject not_vary_normal items in calculate function.
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.
=> [Task] Update Slean link slide and video

Android/setup-project/.sun-ci.yml, Android/setup-project/README.md, Android/setup-project/ktlint.gradle
- [#TicketID](https://edu-redmine.sun-asterisk.vn/issues/???)
- Change number items `completed/total` in admin page.
- I edit js file, inject not_vary_normal items in calculate function.
- Because in previous version - number just depends on `normal` items. But in new version, we have `state` and `confirm_state` depends on both `normal` + `not_normal` items.
=> change ktlint detekt into local setup

FrontEnd/HtmlCss.md, FrontEnd/HtmlCss_en.md, FrontEnd/coding_convention/HtmlCss_en.md, FrontEnd/coding_convention/HtmlCss_vi.md
Bổ sung và cập nhật coding conventions mới nhất cho html, css
[Image HTML VI](https://github.com/binhpt-1239/Training-Guideline/blob/add_coding_convention_html_css/FrontEnd/coding_convention/HtmlCss_vi.md)
[Image HTML EN](https://github.com/binhpt-1239/Training-Guideline/blob/add_coding_convention_html_css/FrontEnd/coding_convention/HtmlCss_en.md)
=> Add coding convention for HTML/CSS
